package com.syscloud.provider.model.vo;

import java.io.Serializable;

public class SysLogWithBLOBs extends SysLog implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.old_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    private String oldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.new_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    private String newValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.old_value
     *
     * @return the value of sys_log.old_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.old_value
     *
     * @param oldValue the value for sys_log.old_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue == null ? null : oldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.new_value
     *
     * @return the value of sys_log.new_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.new_value
     *
     * @param newValue the value for sys_log.new_value
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }
}