server:
  port: 8761
spring:
  profiles:
    active: dev
  application:
    name: hmst-eureka
logging:
  config: classpath:log-spring.xml
#logging:
#  level.root: info
#  path: logs/
#  file: ${spring.application.name}.log