server:
  port: ${hmstcloud.server.monitor.port:8781}
spring:
  application:
    name: hmst-monitor
  profiles:
    active: dev
  security:
    user:
      name: "hm"
      password: "123456"
  mail:
    host:
    username: 13548668976@163.com
    password: hm1986
    protocol: smtp
    test-connection: true
    default-encoding: utf-8
#    properties:
#      mail:
#        debug: true
#        smtp:
#          auth: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
#          starttls:
#            enable: true
#            required: true
  boot:
    admin:
      notify:
        mail:
          to: 674703614@qq.com
          from: 13548668976@163.com
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    healthCheckUrlPath: /actuator/health
    metadata-map:
       user.name: "hm"
       user.password: "123456"
  client:
    registerWithEureka: false
    fetchRegistry: false
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://hm:123456@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  config: classpath:log-spring.xml
