spring:
  application:
    name: hmst-configportal
  profiles:
    active: ${apollo_profile}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.170.17:3306/apolloportaldb?characterEncoding=utf-8
    username: root
    password: Hm123456
    druid:
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
security:
    basic:
      enabled: true
    user:
      name: hm  # 认证用户名
      password: 123456 # 认证密码
server:
  port: 8784
logging:
  config: classpath:log-spring.xml
endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: true
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


