server:
  port: 8762
eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
           defaultZone: http://hm:123456@localhost:8761/eureka/
                    # docker 部署开启
            #defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
      name: hmst-gateway
  rabbitmq:
      host: 47.98.170.17
      port:  5672
      username: hm
      password: 123456
  redis:
    host: 47.98.170.17
    port: 6379
    password: Hm123456
    timeout: 2000
  session:
    store-type: redis
  cloud:
    gateway:
      routes:
        # =====================================
      - id: provider-user
        uri: lb://provider-user
        order: 8003
        predicates:
        - Path=/user-service/**
        filters:
        - StripPrefix=1
      - id: hmst-monitor
        uri: lb://hmst-monitor
        order: 8001
        predicates:
        - Path=/monitor-service/**
        filters:
        - StripPrefix=1
      - id: hmst-eureka
        uri: lb://hmst-eureka
        order: 8000
        predicates:
        - Path=/eureka-service/**
        filters:
        - StripPrefix=1
#
#      - id: hmst-zipkin
#        uri: lb://hmst-zipkin
#        order: 8002
#        predicates:
#        - Path=/zipkin-service/**
#        filters:
#        - StripPrefix=1
#      - id: hmst-configure-admin
#        uri: lb://hmst-configure-admin
#        order: 8004
#        predicates:
#        - Path=/configure-admin-service/**
#        filters:
#        - StripPrefix=1
#      - id: hmst-configure-service
#        uri: lb://hmst-configure-service
#        order: 8004
#        predicates:
#        - Path=/configure-admin-service/**
#        filters:
#        - StripPrefix=1

logging:
  config: classpath:log-spring.xml