server:
  port: 8762

eureka:
    instance:
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
        # docker 部署开启
#        prefer-ip-address: true
#        ip-address: 127.0.0.1
    client:
        serviceUrl:
           defaultZone: http://localhost:8761/eureka/
                    # docker 部署开启
            #defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
      name: hmst-gateway
  rabbitmq:
      host: 47.98.170.17
      port:  5672
      username: hm
      password: 123456
  redis:
    host: 47.98.170.17
    port: 6379
    password: Hm123456
    timeout: 2000
  session:
    store-type: redis
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        # =====================================
            - id: provider-user
              uri: lb://provider-user
              order: 8000
              predicates:
              - Path=/userapi/**
              filters:
              - StripPrefix=1
logging:
  config: classpath:log-spring.xml