server:
  port: ${hmstcloud.server.provider.user.port:8771}
spring:
  application:
    name: provider-user
  profiles:
    active: dev
  redis:
    host: 120.79.53.121
    port: 7000
    password: Hm123456
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz98og42mf98p7vf1ao.mysql.rds.aliyuncs.com:3306/user?characterEncoding=utf-8&useSSL=true
    username: root
    password: Hm123456
    druid:
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  session:
    store-type: redis

