server:
  port: ${hmstcloud.server.provider.user.port:8771}
spring:
  application:
    name: provider-user
  profiles:
    active: dev
  rabbitmq:
    host: 47.98.170.17
    port: 5672
    username: hm
    password: 123456
  zipkin:
    rabbitmq:
      queue: zipkin
  redis:
    host: 47.98.170.17
    port: 6379
    password: Hm123456
    timeout: 2000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.170.17:3306/user?characterEncoding=utf-8&useSSL=false
    username: root
    password: Hm123456
    druid:
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
jwt:
  token-header: token
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45
client:
  id: hmst-auth
  secret: 123456
  token-header: x-client-token
  expire: 14400
  rsa-secret: x2318^^(*WRYQWR(QW&T
logging:
  config: classpath:log-spring.xml


