package com.syscloud.provider.user.mapper;

import com.syscloud.provider.user.model.example.SysUserExample;
import com.syscloud.provider.user.model.query.PageQuery;
import com.syscloud.provider.user.model.vo.SysUser;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    int countByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    int deleteByExample(SysUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user
     *
     * @mbggenerated Thu Dec 21 23:20:45 CST 2017
     */
    List<SysUser> selectByExample(SysUserExample example);
    SysUser selectByPrimaryKey(Integer id);
    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);
    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);
    int updateByPrimaryKeySelective(SysUser record);
    int updateByPrimaryKey(SysUser record);
    SysUser findByKeword(String keyword);
    int conuntByMail(@Param("mail") String mail, @Param("id") Integer id);
    int conuntByTelphone(@Param("telephone") String telephone, @Param("id") Integer id);
    int conuntByDeptId(@Param("deptId") Integer deptId);
    List<SysUser> getPageByDeptId(@Param("deptId") int deptId, @Param("page") PageQuery page, @Param("keyword") String keyword);
    List<SysUser> getByIdList(@Param("idList") List<Integer> idList);
    List<SysUser> getAll();
}