server:
  port: 8782
spring:
  profiles:
    active: dev
  application:
    name: hmst-zipkin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zipkin?useSSL=false&characterEncoding=utf-8
    username: root
    password: Hm123456
    druid:
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
     #zipkin数据保存到数据库中需要进行如下配置
     #表示当前程序不使用sleuth
    sleuth:
      enabled: false
     #表示zipkin数据存储方式是mysql
zipkin:
  storage:
    type: mysql
  collector:
    rabbitmq:
      addresses: localhost:5672
      password: 123456
      username: hm
      queue: zipkin
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadata-map:
       user.name: "hm"
       user.password: "123456"
       statusPageUrlPath: /actuator/info
       healthCheckUrlPath: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://hm:123456@localhost:8761/eureka/

#zipkin:
 # storage:
  #  type: elasticsearch
   # elasticsearch:
    #  hosts: 47.106.140.208:9200
     # max-requests: 64
      #index: zipkin
      #index-shards: 5
      #index-replicas: 1
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
management:
  security:
    enabled: false
  context-path: /actuator